---
Name: iqsearchresultspage
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - IQnection\SearchResultsPage\Extensions\SiteTreeExtension
PageController:
  extensions:
    - IQnection\SearchResultsPage\Extensions\PageControllerExtension